- hosts: localhost
  tasks:
  - ec2:
      key_name: Demokey
      instance_type: t2.micro
      image: ami-00874d747dde814fa
      region: us-east-1
      count: 1
      instance_tags:
        name: "Ansible-LB"
      group_id: sg-04deb17b179d0b2b0
  - ec2:
      key_name: Demokey
      instance_type: t2.micro
      image: ami-00874d747dde814fa
      region: us-east-1
      count: 4
      instance_tags:
        name: "Ansible-web"
      group_id: sg-04deb17b179d0b2b0
