- hosts: localhost
  become: true
  tasks:
    - name: Launching EC2 instances
      community.aws.ec2_instance:
        aws_access_key: ASIATSVOPX3DJNEQD56K
        aws_secret_key: Q4Q3oAO5FUopBx3OwQX/EhPMY97oyHR+rY4Zr3lx
        key_name: Demokey.pem
        security_group: "{{ aws_security_group }}"
        instance_type: t2.micro
        image_id: ami-00874d747dde814fa
        state: present
        wait: yes
        wait_timeout: 300
        region: us-east-1
        tags:
           Name: "{{ item.value.name }}"
        detailed_monitoring: no
        vpc_subnet_id: "{{ vpc_subnet_list | random }}"
        network:
          assign_public_ip: yes

    - name: Create Security group
      amazon.aws.ec2_group:
        name: sg
        description: 'Security Group with SSH and HTTP rules'
        vpc_id: vpc-0efa6947caf6fb2a7
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22 

# create elb
    - name: Create Amazon ELB
      amazon.aws.ec2_elb_lb:
        profile: "{{ aws_boto_profile }}"
        name: "{{ aws_elb_app_lb }}"
        region: us-east-1
        zones:
          - "{{ ap_zone1 }}"
          - "{{ ap_zone2 }}"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
            proxy_protocol: True
        state: present
      register: elbcreated
